### ISSUE TITLE
Control gamma factor

### ISSUE THREAD

**Issue by deval281shah** [ArdhenduBehera/RAFA-Net#3]
Hi,

Thank you very much for providing your code! I am trying to train on the 300LP dataset and test on AFLW2000. I am confused about the gamma factor. As mentioned in the paper, gamma equal to 0.2 and 0.3 results in the lowest error. How do I control that parameter? Is it using self.bb_min and  self.bb_width in the pose_data_augmentor.py?

**Comment by ArdhenduBehera** [comment]
For training it is randomized using bb_width=0.5, bb_min=0.0 i.e., border_width is randomly generated between 0 and 0.5. For testing you fix the border_width to 0.2 0r 0.3.

**Comment by deval281shah** [comment]
Thank you very much!
